services:

  mysql:
    image: mysql:8.4
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./docker:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    networks:
      - e_com
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  product-service:
    image: product-service:1.0
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "9001:9001"
    networks:
      - e_com
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
networks:
  e_com:
    driver: bridge